### ISSUE TITLE
Advice for who starred the old repository

### ISSUE THREAD

**Issue by gusbemacbe** [dracula/prism#1]
Hello @jonleopard and anyone who starred and forked the old repository,

As you starred the old repository yesterday, I have upgraded the theme, fixing the bugs and finishing the job. But I have removed the old repository, then I have transferred to new official repository on Dracula Themes. You can star again and download the official theme here now. Check the install. 

Thank you for your attention and understanding!

**Comment by jonleopard** [comment]
Thank you for the info @gusbemacbe!
