### ISSUE TITLE
Can I use it for Vue?

### ISSUE THREAD

**Issue by jd-0001** [dracula/prism#13]
Hi,
I really love dracula and I am glad that I found this. However, I think this doesn't support Vue yet.

![image](https://user-images.githubusercontent.com/47495003/93317514-38e47580-f82b-11ea-9e9c-372064a279d8.png)

How dracula in my vs code highlight it:

![image](https://user-images.githubusercontent.com/47495003/93317575-4b5eaf00-f82b-11ea-9f7f-14e3389f4cde.png)

**Comment by gusbemacbe** [comment]
Hello @jd-0001 

Take https://www.npmjs.com/package/vue-prism-component and take the file https://github.com/dracula/prism/blob/master/css/dracula-prism.css to `prismjs/themes/` or create `css/prismjs/themes` with this file, and replace `import 'prismjs/themes/dracula-prism.css'` with `import 'css/prismjs/themes/dracula-prism.css'`.

**Comment by jd-0001** [comment]
Ohk. I will check it and will let you know.

**Comment by jd-0001** [comment]
@gusbemacbe 

Hi checked it the same way you told me but the result is the same as I showed in the screenshot. I tried to check the source code of vs code Dracula but it was in yml and not css so I didn't wasted my time there to find the exact issue.

I am attaching another image with dev tool.
![Screenshot from 2020-09-24 12-40-32](https://user-images.githubusercontent.com/47495003/94112559-40c39b80-fe63-11ea-845b-ecaea283f680.png)

I guess this can be due to version mismatch??

**Comment by jd-0001** [comment]
Hey @gusbemacbe 

Yes this was due to version mismatch. I used prismjs `1.14.0` same as your css's header and it worked!

Sorry for the trouble.

One last thing I would like to ask is this problem still exist if we use latest prismjs `1.21.0`.

Is there any plan to make compatible for the latest version??

**Comment by gusbemacbe** [comment]
> One last thing I would like to ask is this problem still exist if we use latest prismjs `1.21.0`.
> 
> Is there any plan to make compatible for the latest version??

The `dracula-prism.css` is always compatible with any past, present and future version of Prismjs. Do not use Dracula's `prism.js`, use Dracula's `dracula-prism.css`.

**Comment by jd-0001** [comment]
Certainly, I am not using dracula's `prism.js` I am using prismjs from npm module:
```
import 'prismjs'
// Here my dracula CSS path
import Prism from 'vue-prism-component'
```

Anyways, if it's compatible then there are no worries. I will try it in my docs and will let you know if there's any issues.

Thanks for your time. Regards.
