### ISSUE TITLE
lacking `mark` colors

### ISSUE THREAD

**Issue by zebapy** [dracula/prism#14]
highlighted lines are lacking some nice dracula styles

![image](https://user-images.githubusercontent.com/2199845/107727843-532b5e00-6cba-11eb-8a7d-2ef2ee350b35.png)

**Comment by gusbemacbe** [comment]
Hello @zebapy 

Is it JavaScript?

**Comment by gusbemacbe** [comment]
Please, can you share your code that I'll test?

**Comment by zebapy** [comment]
@gusbemacbe  i'm using examples from eleventy syntax highlight https://www.11ty.dev/docs/plugins/syntaxhighlight/#markdown-highlighter see the JS example


_backticks_ js/1,3-5
function myFunction() {
  // …
  return true;
}
_backticks_

(_backticks_ cause idk how to show the redundant example code at the moment)

**Comment by gusbemacbe** [comment]
@zebapy 

Done:

![imagem](https://user-images.githubusercontent.com/2257024/108282923-2f0bc900-7161-11eb-8575-143d8774bd3b.png)

**Comment by gusbemacbe** [comment]
Please test it, @zebapy.
