### ISSUE TITLE
CDN is not working.

### ISSUE THREAD

**Issue by Divaksh** [dracula/prism#15]
The following CDN is throwing 404
https://unpkg.com/dracula-prism/css/dracula-prism.css
https://unpkg.com/dracula-prism@2.0.0/css/dracula-prism.css

**Comment by gusbemacbe** [comment]
@zenorocha 

The Prism page needs to be updated. I pushed a new version, but your page didn't update itself.

**Comment by gusbemacbe** [comment]
> The following CDN is throwing 404
> https://unpkg.com/dracula-prism/css/dracula-prism.css
> https://unpkg.com/dracula-prism@2.0.0/css/dracula-prism.css

@Divaksh 

The page did not update itself when I pushed a new version. 

Now, it's:

https://unpkg.com/dracula-prism/dist/css/dracula-prism.css
https://unpkg.com/dracula-prism@2.0.0/dist/css/dracula-prism.css

And minified files

https://unpkg.com/dracula-prism/dist/css/dracula-prism.min.css
https://unpkg.com/dracula-prism@2.0.0/dist/css/dracula-prism.min.css

**Comment by Divaksh** [comment]
Thank you, it helped. It would be great if some instructions are added for the npm package page as well. I couldn't figure out how to import it in ReactJS.

**Comment by gusbemacbe** [comment]
Noted. I will add the instructions for ReactJS users tonight.

**Comment by gusbemacbe** [comment]
Done, @Divaksh. Please check.
