### ISSUE TITLE
npm package `dracula-prism` includes dev dependencies

### ISSUE THREAD

**Issue by Vestride** [dracula/prism#16]
Because this package specifies all its dependencies in the `dependency` property of the `package.json` (instead of `devDependency`), projects which install this package also install each one, which they may not need.

My codebase, for example, now includes `jquery`:

```
$ yarn why jquery
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "jquery"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "jquery@3.6.0"
info Reasons this module exists
   - "dracula-prism" depends on it
   - Hoisted from "dracula-prism#jquery"
info Disk size without dependencies: "1.71MB"
info Disk size with unique dependencies: "1.71MB"
info Disk size with transitive dependencies: "1.71MB"
info Number of shared dependencies: 0
```

**Comment by gusbemacbe** [comment]
Done. Right?

**Comment by Vestride** [comment]
That is one way to fix this if you're not actually using jQuery (by which I mean you don't import it from somewhere for your test files or docs).

You can think of it this way: if I, the user of your package, need an npm package from your package.json in order for me to use your package, it should be a regular dependency. If I can use your package without it, it should be a dev dependency.

Let's use the @testing-library packages as an example. Since you only use them for tests in your repository, I (in my project) don't need to install them, so they should be dev dependencies.

**Comment by gusbemacbe** [comment]
Well, we don't depend on jQuery.

**Comment by Vestride** [comment]
#18
