### ISSUE TITLE
npm package `dracula-prism` includes source and test files 

### ISSUE THREAD

**Issue by Vestride** [dracula/prism#17]
Since the `package.json` does not use the [`files`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) property (or have an `.npmignore` file), npm includes all the files in the directory in the built package.

Example from my `node_modules` directory:

<img width="183" alt="Screen Shot 2021-04-04 at 1 26 43 PM" src="https://user-images.githubusercontent.com/963921/113520693-cc706000-9549-11eb-93a2-dcaac43b9343.png">

**Comment by gusbemacbe** [comment]
Do you mean I add the file `.npmignore` for ignoring the `files`, @Vestride?

**Comment by Vestride** [comment]
You can do either. Personally I like the files property in the package.json.

**Comment by gusbemacbe** [comment]
Then you can make a pull request if you want.

**Comment by Vestride** [comment]
#19
