### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by jefrydco** [dracula/prism#8]
Hi!

Do you have any plan to publish this repo to NPM?

**Comment by gusbemacbe** [comment]
HI @jefrydco 

I am not a member of Dracula organisation, I am only a contributor. You can ask @AurelienLourot, which is reponsible for the Dracula organisation.

If you would like to install separately Dracula Prism with `npm`, I may ask for @AurelienLourot's authorisation.

**Comment by jefrydco** [comment]
Great! Thanks for helping with that. It will be easier to use this theme via NPM.

**Comment by AurelienLourot** [comment]
Hi, I'm also only a contributor :)

**Comment by gusbemacbe** [comment]
Too bad, @AurelienLourot, can I know who the owner and officers are, so I will ask for their authorisation?

**Comment by AurelienLourot** [comment]
The creator of Dracula is @zenorocha. I see that the organization has other owners but I'm not sure if they are active. The best is probably to post on [Slack](https://slack.draculatheme.com/).

**Comment by hacknug** [comment]
Just wrote to @zenorocha asking about this. Will get back to you when he does!

**Comment by gusbemacbe** [comment]
Hi @jefrydco, @AurelienLourot, @AurelienLourot  and @hacknug.

As I have already enough knowledge of npmpjs, I have just published the repo to npmjs. It is read. If you already built it before, let me know, and if you did not build it, but want me to transfer the package to you npmjs organisation, let me know too. 

Here is: https://www.npmjs.com/package/dracula-prism

**Comment by gusbemacbe** [comment]
I have just updated the README.

**Comment by zenorocha** [comment]
Hey @gusbemacbe, let's try to move this to the new Dracula org on NPM. What's your npm username?

**Comment by gusbemacbe** [comment]
Hi @zenorocha !

My NPM username is gusbemacbe.

**Comment by zenorocha** [comment]
Just sent you an invite

**Comment by gusbemacbe** [comment]
@zenorocha 

Done, nut NPM site does not recognise the username `dracula` and declines to transfer my package to your organisation.

**Comment by zenorocha** [comment]
Try now

**Comment by gusbemacbe** [comment]
@zenorocha 

Here is the preview :-(

![image](https://user-images.githubusercontent.com/2257024/73795290-077dd480-4789-11ea-9c80-db365fd2dd8a.png)

**Comment by gusbemacbe** [comment]
It worked now.

I had to enter the organization, and to add myself tot he developers list, and added the exiting package. 

![image](https://user-images.githubusercontent.com/2257024/73795497-85da7680-4789-11ea-9d47-95ad6c4a6d5a.png)
